# Generated by Django 5.1.6 on 2025-02-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapplication',
            name='partner_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerapplication',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
